### PR TITLE
New synth update

### PR DESCRIPTION
**Pull request by josephwb**
Treemachine relies upon this branch.
Basically a bunch of updates related to the new loading and synthesis procedure. The .bitarray package contains faster more efficient implementations of sets. This also begins to use the new TreeNode interface that should obviate the need for lots of replicate code to deal with nexsons vs. jadetree objects

### CODE REVIEW

**Comment by josephwb** [comment]
This, in turn, requires the "new-synth-update" of [jade](https://github.com/FePhyFoFum/jade).

**Comment by josephwb** [comment]
Thinking of moving jade over to OpenTree, as we are the only ones using it. If so, would just have to alter the README and "mvn_load_dependencies.sh" to reflect new location.

**Comment by jar398** [comment]
A move would also require a small change
to deploy/setup/install-neo4j-app.sh in the opentree repo.

**Comment by chinchliff** [comment]
Really, the jade classes should be included in ot-base--there is no reason why the jade repo is separate except that originally we had thought perhaps it would be used by other tools. However, now is not the time for to move those classes. Moving the entire jade repo to the ot umbrella is an intermediate step that requires many fewer changes to other things.

**Comment by jar398** [comment]
Agree on both points.

**Comment by jar398** [comment]
Is this PR backward compatible? I.e. will it work with old versions of treemachine and its other clients?

**Comment by chinchliff** [comment]
I'm not sure, but I think it is likely not backward compatible... But it's
been a while, and I haven't tried it to see.

**Comment by chinchliff** [comment]
Basically a bunch of updates related to the new loading and synthesis procedure. The .bitarray package contains faster more efficient implementations of sets. This also begins to use the new TreeNode interface that should obviate the need for lots of replicate code to deal with nexsons vs. jadetree objects

**Pull request merged**
